name: Deploy

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    concurrency: ci-${{ github.ref }}

    runs-on: ubuntu-latest

    steps:
      - name: CheckoutRepository
        uses: actions/checkout@v3

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/
