name: BuildWebpack

on: [push, pull_request]

jobs:
  build:
    concurrency: ci-${{ github.ref }}

    runs-on: ubuntu-latest

    steps:
    - name: CheckoutRepository
      uses: actions/checkout@v3

    - name: Set_upNode
      uses: actions/setup-node@v3
      with:
        node-version: "16.x"

    - name: Install
      run: npm install --force

    - name: Build
      run: npm run build --if-present

    - name: LintJS
      run: npm run lint:js

    - name: LintCSS
      run: npm run lint:css
