name: webpack

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: CheckoutRepository
      uses: actions/checkout@master

    - name: Set_upNode
      uses: actions/setup-node@v1
      with:
        node-version: "16.x"

    - name: Install
      run: npm install --force

    - name: Build
      run: npm run build

    - name: Deploy
      uses: actions/checkout@master
      with:
        target_branch: master
        build_dir: dist
      env:
        GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
