name: webpack

on: [push, pull_request]

jobs:
  build:
    concurrency: ci-${{ github.ref }}

    runs-on: ubuntu-latest

    steps:
    - name: CheckoutRepository
      uses: actions/checkout@v3

    - name: Set_upNode
      uses: actions/setup-node@v3
      with:
        node-version: "16.x"

    - name: InstallAndBuild
      run: |
        npm install --force
        npm run build

    - name: LintJS
      run: npm run lint:js

    - name: LintCSS
      run: npm run lint:css
