name: webpack

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: CheckoutRepository
      uses: actions/checkout@master

    - name: Set_upNode
      uses: actions/setup-node@v1
      with:
        node-version: "16.x"

    - name: Install
      run: npm install --force

    - name: Build
      run: npm run build
