name: webpack

on:
  push:
    branches: [ * ]
  pull_request:
    branches: [ * ]

jobs:
  build:
    concurrency: ci-${{ github.ref }}

    runs-on: ubuntu-latest

    steps:
    - name: CheckoutRepository
      uses: actions/checkout@v3

    - name: Set_upNode
      uses: actions/setup-node@v1
      with:
        node-version: "16.x"

    - name: Install
      run: npm install --force

    - name: Build
      run: npm run build

    - name: Lint
      run: |
        npm run lint:js
        npm run lint:css
