name: webpack

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: GetDir
      run: echo ls

    - name: Install
      run: |
        npm install
        npm start

    - name: Build
      run: npm run build
